 version: 2.1
 jobs:
   validate:
     docker:
       - image: 'cimg/node:14.14.0'
     steps:
       - run: sudo npm install -g @apidevtools/swagger-cli
       - run: swagger-cli --version
       - checkout
       - run: find endpoints -name \*.yaml -a ! -name _\*.yaml -exec swagger-cli validate -d -t yaml {} \;
 workflows:
   version: 2
   validation:
     jobs:
       - validate
