openapi: 3.0.0
info:
  version: 6.0.0
  title: Common Error Responses
  description: Commercial Instructions Schema
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  responses:
    Success:
      description: 200 OK - request accepted successfully
      content:
        application/json:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/AcceptedResponse'
          example:
            $ref: '../examples\6.0.0\GenericResponses\JSON\200Success.json'
        application/xml:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/AcceptedResponse'
          example:
            $ref: '../examples\6.0.0\GenericResponses\XML\200Success.xml'
    Created:
      description: 201 Created - request created successfully
      content:
        application/json:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/AcceptedResponse'
          example:
            $ref: '../examples\6.0.0\GenericResponses\JSON\201Created.json'
        application/xml:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/AcceptedResponse'
          example:
            $ref: '../examples\6.0.0\GenericResponses\XML\201Created.xml'
    Accepted:
      description: 'Accepted - request accepted, Actual response will follow at later time'
      content:
        application/json:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/AcceptedResponse'
          example:
            $ref: '../examples\6.0.0\GenericResponses\JSON\202Accepted.json'
        application/xml:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/AcceptedResponse'
          example:
            $ref: '../examples\6.0.0\GenericResponses\XML\202Accepted.xml'
    BadRequest:
      description: Bad Request - payload is ill formed or contains invalid data
      content:
        application/json:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/Error'
          example:
            $ref: '../examples\6.0.0\GenericResponses\JSON\400BadRequest.json'
        application/xml:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/Error'
          example:
            $ref: '../examples\6.0.0\GenericResponses\XML\400BadRequest.xml'
    Unauthorized:
      description: 'Unauthorized - Unauthorized, invalid credentials or expired access token'
      headers:
        WWW-Authenticate:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/Error'
          example:
            $ref: '../examples\6.0.0\GenericResponses\JSON\401Unauthorized.json'
        application/xml:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/Error'
          example:
            $ref: '../examples\6.0.0\GenericResponses\XML\401Unauthorized.xml'
    Forbidden:
      description: 'Forbidden, additional previliges are needed'
      content:
        application/json:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/Error'
          example:
            $ref: '../examples\6.0.0\GenericResponses\JSON\403Forbidden.json'
        application/xml:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/Error'
          example:
            $ref: '../examples\6.0.0\GenericResponses\XML\403Forbidden.xml'
    NotFound:
      description: 'Not Found, Requested entity does not exist'
      content:
        application/json:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/Error'
          example:
            $ref: '../examples\6.0.0\GenericResponses\JSON\404NotFound.json'
        application/xml:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/Error'
          example:
            $ref: '../examples\6.0.0\GenericResponses\XML\404NotFound.xml'
    NotAllowed:
      description: 'Not Allowed, Requested operation is not allowed on entity'
      content:
        application/json:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/Error'
          example:
            $ref: '../examples\6.0.0\GenericResponses\JSON\405NotAllowed.json'
        application/xml:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/Error'
          example:
            $ref: '../examples\6.0.0\GenericResponses\XML\405NotAllowed.xml'
    Unexpected:
      description: Unexpected error occured
      content:
        application/json:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/Error'
          example:
            $ref: '../examples\6.0.0\GenericResponses\JSON\500Error.json'
        application/xml:
          schema:
            $ref: 'commonSchemas.yaml#/components/schemas/Error'
          example:
            $ref: '../examples\6.0.0\GenericResponses\XML\500Error.xml'
