openapi: 3.0.0
info:
  version: 6.0.0
  title: Inventory Avails Schemas
  description: Inventory Avails Schemas
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    BuyerInventoryAvailsSubscription:
      description: Schema allows the buyer to formulate a query for Inventory meeting the listed conditions
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        name:
          description: Buyer request reference name
          type: string
        mediaOutlets:
          description: Array of mediaOutlet objects being requested
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
          minItems: 1
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        contacts:
          description: Array of Contact objects
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        dayOfWeek:
          $ref: 'commonSchemas.yaml#/components/schemas/DayOfWeek'
        timeWindows:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/TimeWindow'
        guidelines:
          description: Array of Guideline objects being requested
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Guideline'
        isPolitical:
          description: Indicate that rates requested are for a political campaign
          type: boolean
        inventoryTypes:
          description: ArrayList of InventoryTypes being requested
          type: array
          items:
            type: string
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        externalComment:
          description: Free form text to accommodate transaction comments and/or activities outside the TIP flow
          type: string
        audienceSegments:
          description: Array of AudienceSegment objects being requested
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudienceSegment'
          minItems: 1
        pricingMetricOptions:
          description: Array of PricingMetricsOption objects being requested
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/PricingMetricOption'
        frequency:
          $ref: 'commonSchemas.yaml#/components/schemas/Frequency'
        startDate:
          oneOf:
            - $ref: 'commonSchemas.yaml#/components/schemas/DynamicDate'
            - type: string
              format: date
        endDate:
          oneOf:
            - $ref: 'commonSchemas.yaml#/components/schemas/DynamicDate'
            - type: string
              format: date
      required:
        - transactionHeader
        - mediaOutlets
        - isPolitical
    SellerInventoryAvails:
      description: >-
        Schema defines the Seller response to previously solicited InventoryAvails request
        from the buyer, or if unsolicited provides the buyer with the catalog of selling
        products, and optionally provide pricing and audience information
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        dateSubmitted:
          description: Seller's submit date for the response
          type: string
          format: date
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        contacts:
          description: Array of Contacts
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
          minItems: 1
        rateCard:
          $ref: 'commonSchemas.yaml#/components/schemas/RateCard'
        isPolitical:
          description: Indicates that pricing being supplied is political
          type: boolean
        mediaOutlets:
          description: Array of MediaOutlets contained in the InventoryAvails
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
          minItems: 1
        audienceSegments:
          description: Array of AudienceSegments contained in the InventoryAvails
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudienceSegmentDetail'
          nullable: True
        availWindow:
          $ref: 'commonSchemas.yaml#/components/schemas/DateWindow'
        salesElements:
          description: Array of SalesElements contained in the InventoryAvails
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/SalesElement'
          minItems: 1
      required:
        - transactionHeader
        - dateSubmitted
        - isPolitical
        - mediaOutlets
        - availWindow
        - salesElements
      xml:
        name: SellerInventoryAvailsRequest
