openapi: 3.0.0
info:
  version: 6.0.0
  title: Log Time Schemas
  description: >-
    Allows the seller to send to the buyer the log times information. No Request from
    buyer is required
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    SellerLogtimes:
      description: Top level element for Logtimes Seller
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        externalComment:
          description: String that indicates additional information the seller can send to the buyer
          type: string
        mediaOutlets:
          description: Array of MediaOutlet objects
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        units:
          description: Units listed in the API units can be defined by the system that is creating the API.
          type: array
          items:
            $ref: '#/components/schemas/Unit'
      required:
        - transactionHeader
        - mediaOutlets
        - units
    Unit:
      description: Unit detail information
      properties:
        unitId:
          description: >-
            Seller generated unique number for unit (ID will likely change if unit is moved to
            another week during recon process).
          type: string
        referenceIds:
          description: >-
            Array of ReferenceId objects containing the order id references; may also contain
            originating RFP and Proposal id and source references
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
          minItems: 1
        lineReferences:
          description: >-
            Array of identifier objects to identify a line id and system source; note- once the
            identifier object has been adopted the goal is to remove existing lineNum
            and lineReference
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Identifier'
        cpeCode:
          $ref: 'commonSchemas.yaml#/components/schemas/CpeCode'
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        salesElementHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/SalesElementHeader'
        program:
          description: This indicates the program the spot aired in -  'as-aired' information
          type: string
        daypart:
          description: This indicates the daypart the spot aired in -  'as-aired' information
          type: string
        inventoryType:
          description: Type of advertising such as a commercial, billboard or other types of advertisement
          type: string
        linkType:
          $ref: 'commonSchemas.yaml#/components/schemas/LinkType'
        isMakegood:
          description: Indicates if the spot is a makegood
          type: boolean
        isAdu:
          description: >-
            Audience Deficiency Unit; Units of commercial advertising inventory made available
            to advertisers as fulfillment for the inventory the advertisers purchased that ran
            in programs that under-delivered on contracted audience demographic ratings
          type: boolean
        preemptUnitIds:
          description: >-
            ArrayList of the 'original' preempted unit being resolved when the isMakegood
            indicator is 'Y';  a makegood unit may be resolved by one too many preempt spots
          type: array
          items:
            type: string
        isBonus:
          description: >-
            $0 (i.e., free) ad impressions/pricing that a publisher includes with paid media
            to maximize the overall proposal/order
          type: boolean
        airedLength:
          description: Length of commercial unit
          type: integer
        bookedLength:
          description: Actual lenth of commerical unit
          type: integer
        rate:
          description: Gross unit rate
          type: number
          format: float
        creative:
          $ref: 'commonSchemas.yaml#/components/schemas/Creative'
        status:
          description: >-
            Indicated the airing status for the spot
            Aired  = 'as-aired' reconciliation for the spot is complete
            No Run = spot either did not run or didn't run as contracted when the broadcast
            log was played out
            Scheduled  = spot is placed on a pre log that has not yet been played out
            Finalized = spot is placed on a log that is in a 'final status' and ready to be
            played out and the spot is locked from edits
            Not Scheduled = spot has not yet been placed on a future broadcast log
            Preempted = spot has been removed from a future broadcast log; the buyer will be
            offered a makegood or issued a credit
          type: string
          enum:
            - Aired
            - Scheduled
            - No Run
            - Finalized
            - Not Scheduled
            - Preempted
        isCredit:
          description: Indicate if the spot was issued a credit due to a discrepancy
          type: boolean
        timePeriods:
          description: >-
            Array of TimePeriod objects indicating SalesElement ordered day and time
            period constraints
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/TimePeriod'
        dateTime:
          description: Not required when unit's status is 'No Run'
          $ref: 'commonSchemas.yaml#/components/schemas/DateTime'
        childUnits:
          description: Array of ChildUnit objects
          type: array
          items:
            $ref: '#/components/schemas/ChildUnit'
      required:
        - unitId
        - referenceIds
        - lineReferences
        - advertiser
        - product
        - salesElementHeader
        - airedLength
        - status
    ChildUnit:
      description: >-
        Child unit details for footprint unit to support Audience Network, Diginet or other
        forms of 'child' units
      properties:
        unitId:
          description: >-
            Seller generated identifier for the child spot; conditional when there is a 'parent'
            unit is sold as a footprint
          type: string
        salesElementHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/SalesElementHeader'
        rate:
          description: Gross unit rate
          type: number
          format: float
        creative:
          description: >-
            Array of identifier objects containing the creative information; at  least
            one identifier object must be provided if spot status is equal to 'Aired'
            or 'Finalized'
          $ref: 'commonSchemas.yaml#/components/schemas/Creative'
        status:
          description: >-
            Indicated the airing status for the spot -
            Aired  = 'as-aired' reconciliation for the spot is complete
            No Run = spot either did not run or didn't run as contracted when the broadcast
            log was played out
            Scheduled  = spot is placed on a pre log that has not yet been played out
            Finalized = spot is placed on a log that is in a 'final status' and ready to be
            played out and the spot is locked from edits
            Not Scheduled = spot has not yet been placed on a future broadcast log
            Preempted = spot has been removed from a future broadcast log; the buyer will be
            offered a makegood or issued a credit
          type: string
          enum:
            - Aired
            - Scheduled
            - No Run
            - Finalized
            - Not Scheduled
            - Preempted
        dateTime:
          description: Required if the child's unit is equal to 'Aired'
          $ref: 'commonSchemas.yaml#/components/schemas/DateTime'
      required:
        - unitId
        - salesElementHeader
    BuyerLogTimesSubscription:
      description: >-
        Schema allows the buyer to formulate a query for log times information that meet
        the listed conditions
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        name:
          description: Buyer request reference name
          type: string
          example: Post log and reconciled logs only
        referenceIds:
          description: >-
            Array of ReferenceId objects containing the order id references; may also contain
            originating RFP and Proposal id and source references
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
        mediaOutlets:
          description: Array of mediaOutlet objects being requested
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
          minItems: 1
        buyer:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        advertiser:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        contacts:
          description: Array of Contact objects
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        inventoryTypes:
          description: ArrayList of InventoryTypes being requested
          type: array
          items:
            type: string
        statuses:
          description: >-
            Indicated the airing status being requested
            Aired  = 'as-aired' reconciliation for the spot is complete
            No Run = spot either did not run or didn't run as contracted when the broadcast
            log was played out
            Scheduled  = spot is placed on a pre log that has not yet been played out
            Finalized = spot is placed on a log that is in a 'final status' and ready to be
            played out and the spot is locked from edits
            Not Scheduled = spot has not yet been placed on a future broadcast log
            Preempted = spot has been removed from a future broadcast log; the buyer will be
            offered a makegood or issued a credit
          type: array
          items:
            type: string
            enum:
              - Aired
              - Scheduled
              - No Run
              - Finalized
              - Not Scheduled
              - Preempted
        frequency:
          $ref: 'commonSchemas.yaml#/components/schemas/Frequency'
        startDate:
          oneOf:
            - $ref: 'commonSchemas.yaml#/components/schemas/DynamicDate'
            - type: string
              format: date
        endDate:
          oneOf:
            - $ref: 'commonSchemas.yaml#/components/schemas/DynamicDate'
            - type: string
              format: date
      required:
        - transactionHeader
        - referenceIds
