openapi: 3.0.0
info:
  version: 6.0.0
  title: Buyer Order Schemas
  description: Buyer requesting New Order or Order Change Request to Seller
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    BuyerOrders:
      description: >-
        Represent the data necessary to describe an order including terms, dates, products,
        media outlets in addition to all reference data
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          description: >-
            Array of ReferenceId objects containing the order id and source references; may also
            contain originating RFP and Proposal id and source references
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
          minItems: 1
        orderBookedDate:
          description: Date in which the buyer submitted the order, this is the original book date
          type: string
          format: date
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        commission:
          description: Buyer commission percentage amount
          type: number
          format: float
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        budgets:
          description: Array of Budget objects containing gross total budget and budget allocations
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Budget'
        cpeCode:
          $ref: 'commonSchemas.yaml#/components/schemas/CpeCode'
        contacts:
          description: Array of Contact objects
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        revenueType:
          description: Indicates the type of payment term for the order; extended enum values are allowed
          type: string
          enum:
            - Cash
            - Barter
            - Trade
        businessType:
          description: Defined business type for the order
          type: string
        localNational:
          description: Indicates the marketplace; extended enum values are allowed
          type: string
          enum:
            - Local
            - National
        dealYear:
          description: Broadcast year for the order
          type: string
        billingOption:
          $ref: 'commonSchemas.yaml#/components/schemas/BillingOption'
        isEquivalized:
          description: >-
            Indicates if the impressions are equivalized (weighted) down or up from a base 30-second
            unit using a ratio of the unit's length
          type: boolean
        dateWindows:
          description: >-
            Array of DateWindow objects indicating the order's valid start and end dates; Hiatus
            dates are excluded
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/DateWindow'
        cancellationTerms:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/CancellationTerm'
        timeSeparations:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/TimeSeparation'
        termsOfSales:
          description: Information specific to payment terms, preemption status, etc.
          type: string
        externalComment:
          description: Free form text to accommodate transaction comments and/or activities outside the TIP flow
          type: string
        rateCard:
          $ref: 'commonSchemas.yaml#/components/schemas/RateCard'
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        mediaOutlets:
          description: Array of MediaOutlet objects being ordered
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        audienceSegments:
          description: Array of AudienceSegment objects being ordered
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudienceSegmentDetail'
        salesElements:
          description: Array of SalesElementsTransaction objects being ordered
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/SalesElementTransaction'
      required:
        - transactionHeader
        - referenceIds
        - orderBookedDate
        - buyer
        - commission
        - contacts
        - revenueType
        - businessType
        - isEquivalized
        - dateWindows
        - mediaOutlets
    SellerOrders:
      description: Schema is an alias to CancelConfirmRecallReject object
      $ref: 'commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
