openapi: 3.0.0
info:
  version: 6.0.0
  title: RFP Schemas
  description: Request For Proposal Schemas
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    BuyerRFPS:
      description: >-
        Schema allows the buyers is able to express the criteria that need to be met when
        responding with a proposal
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          description: Array of ReferenceId objects containing the RFP id and source references
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
          minItems: 1
        dateSubmitted:
          description: RFP submission date
          type: string
          format: date
        dueDate:
          description: Response due date for proposal
          type: string
          format: date
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        commission:
          description: Buyer commission percentage amount
          type: number
          format: float
          example: 15
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        contacts:
          description: Array of Contact objects
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
          minItems: 1
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        budgets:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Budget'
        timePeriodPreferences:
          description: Array of TimePeriod objects containing the buyer's preferences
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/TimePeriod'
          minItems: 1
        marketPreferences:
          description: ArrayList of marketPreferences containing the buyer's preferences
          type: array
          items:
            type: string
            example: [
  "Houston",
  "Austin"
]
        audiencePreferences:
          description: Array of AudienceSegment objects containing the buyer's preferences
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudienceSegment'
        targetingPreferences:
          description: ArrayList of TargetingPreference containing the buyer's preferences
          type: array
          items:
            type: string
            example: [
  "Auto Intenders"
]
        frequencyPreferences:
          description: Array of FrequencyCapping objects containing the buyer's preferences
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/FrequencyCapping'
        unitLengthPreferences:
          description: ArrayList of unitLengthsPreferences containing the buyer's preferences
          type: array
          items:
            type: integer
            example: [
  30,
  15
]
        guidelines:
          description: Array of Guideline objects containing the buyer's preferences
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Guideline'
        objective:
          description: KPI of the overall campaign
          type: string
        comments:
          description: Additional Information
          type: string
        campaignGoals:
          type: array
          items:
            $ref: '#/components/schemas/CampaignGoal'
      required:
        - transactionHeader
        - referenceIds
        - dateSubmitted
        - advertiser
        - contacts
        - timePeriodPreferences
    CampaignGoal:
      properties:
        distributionType:
          description: Indicates the distribution type for the goal; extended enum values are allowed
          type: string
          enum:
            - Media Outlet Type
            - Daypart
            - Market
            - Unit Length
            - AddedValue
            - Quarter
            - Month
            - Week
        distributionMethod:
          description: >-
            Distribution method elements; impressions or GRP distributions pertain to the primary
            audience segment; extended enum values are allowed
          type: string
          enum:
            - Impressions
            - GRPs
            - Units
            - Budget
        distributionName:
          description: >-
            Name associated to the distributionType; for example it could be MediaOutletType
            such as Local Broadcast TV, or a specific Daypart Name, or Specific Quarter Name,
            etc.
          type: string
        distribution:
          description: Indicates if the distributionValue is a percentage or exact value
          type: string
          enum:
            - Percentage
            - Exact Value
        distributionValue:
          description: Distribution goal value
          type: number
          format: float
        distributionOrder:
          description: >-
            Populate when multiple distributions types are defined to define a nesting order
            for the distributions
          type: integer
          minimum: 0
        distributionOrderParent:
          description: Populate when multiple distributions to indicate the parent of a nesting order
          type: integer
          nullable: True
      required:
        - distributionType
        - distributionMethod
        - distributionName
        - distribution
        - distributionValue
        - distributionOrder
        - distributionOrderParent
