openapi: "3.0.0"
info:
  version: 6.0.0
  title: Logtimes
  description: Seller Provides a Logtimes report on the buyer's server
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io/v6.0.0
security:
  - bearerAuth: []

paths:
  /seller/logtimes:
    post:
      tags:
        - Seller
      summary: Seller Creates Logtimes record in the buyer system
      description: >-
        Allows the seller to send to the buyer the log times information. No Request from buyer is
        Required.<br/>
        Supported Transaction Types: New, Change
      operationId: SellerLogtimes
      requestBody:
        description: seller provides the Log Times report to the buyer's system
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/logTimesSchemas.yaml#/components/schemas/SellerLogtimes'
            examples:
              New:
                value:
                  $ref: 'examples\6.0.0\Seller\JSON\LogtimesNew.json'
              Change:
                value:
                  $ref: 'examples\6.0.0\Seller\JSON\LogtimesChange.json'
          application/xml:
            schema:
              $ref: 'schemas/logTimesSchemas.yaml#/components/schemas/SellerLogtimes'
            examples:
              New:
                value:
                  $ref: 'examples\6.0.0\Seller\XML\LogtimesNew.xml'
              Change:
                value:
                  $ref: 'examples\6.0.0\Seller\XML\LogtimesChange.xml'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
  /buyer/logtimes/subscription:
    post:
      tags:
        - Buyer
      summary: Allows the Buyer to initiate a request to subscribe to receive the seller's log time information
      description: >-
          This endpoint is hosted at the seller end. Allows the Buyer to
          to initiate a Request Request to Seller to subscribe to seller's information
          Supported Transaction Types: New, Change, Cancel
      operationId: BuyerLogtimesSubscription
      requestBody:
        description: seller provides the Log Times report to the buyer's system
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/BuyerLogTimesSubscriptionRequest'
            examples:
              New:
                value:
                  $ref: 'examples\6.0.0\Buyer\JSON\LogtimesSubscriptionNew.json'
              Change:
                value:
                  $ref: 'examples\6.0.0\Buyer\JSON\LogtimesSubscriptionChange.json'
              Cancel:
                value:
                  $ref: 'examples\6.0.0\Buyer\JSON\LogtimesSubscriptionCancel.json'
          application/xml:
            schema:
                $ref: '#/components/schemas/BuyerLogTimesSubscriptionRequest'
            examples:
              New:
                value:
                  $ref: 'examples\6.0.0\Buyer\XML\LogtimesSubscriptionNew.xml'
              Change:
                value:
                  $ref: 'examples\6.0.0\Buyer\XML\LogtimesSubscriptionChange.xml'
              Cancel:
                value:
                  $ref: 'examples\6.0.0\Buyer\XML\LogtimesSubscriptionCancel.xml'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    BuyerLogTimesSubscriptionRequest:
      oneOf:
        - $ref: 'schemas/logTimesSchemas.yaml#/components/schemas/BuyerLogTimesSubscription'
        - $ref: 'schemas/commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
      xml:
        name: BuyerLogTimesSubscriptionRequest

