openapi: "3.0.0"
info:
  version: 6.0.0
  title: Makegoods
  description: Makegoods Endpoints
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Forum
    email: tip-mailing-list@tbd.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io/tip/v6.0.0
security:
  - bearerAuth: []

paths:
  /seller/makegood/guidelines:
    post:
      tags:
        - Seller
      summary: Seller submits a request for buyer's makegood guidelines
      description: |
        Allows the seller submits a request for buyer's makegood guidelines<br/>
        Supported Transaction Types: New
      operationId: SellerMakegoodGuidelines
      requestBody:
        description: SellerMakegoodGuidelines
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/makegoodsSchemas.yaml#/components/schemas/SellerMakegoodGuidelines'
            examples:
              New:
                value:
                  $ref: 'examples\6.0.0\Seller\JSON\MakegoodGuidelinesNew.json'
          application/xml:
            schema:
              $ref: 'schemas/makegoodsSchemas.yaml#/components/schemas/SellerMakegoodGuidelines'
            examples:
              New:
                value:
                  $ref: 'examples\6.0.0\Seller\XML\MakegoodGuidelinesNew.xml'
      responses:
        '202': #Accepted
          $ref: 'schemas/commonResponses.yaml#/components/responses/Accepted'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
  /buyer/makegood/guidelines:
    post:
      tags:
        - Buyer
      summary: Buyer responds back to seller with list of makegood guidelines
      description: |
        Buyer responds back to seller with list of makegood guidelines
        Supported Transaction Types: New, Change, Cancel
      operationId: BuyerMakegoodGuidelines
      requestBody:
        description: Makegoods
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuyerMakegoodGuidelinesRequest'
            examples:
              New:
                value:
                  $ref: 'examples\6.0.0\Buyer\JSON\MakegoodGuidelinesNew.json'
              Change:
                value:
                  $ref: 'examples\6.0.0\Buyer\JSON\MakegoodGuidelinesChange.json'
              Cancel:
                value:
                  $ref: 'examples\6.0.0\Buyer\JSON\MakegoodGuidelinesCancel.json'
          application/xml:
            schema:
              $ref: '#/components/schemas/BuyerMakegoodGuidelinesRequest'
            examples:
              New:
                value:
                  $ref: 'examples\6.0.0\Buyer\XML\MakegoodGuidelinesNew.xml'
              Change:
                value:
                  $ref: 'examples\6.0.0\Buyer\XML\MakegoodGuidelinesChange.xml'
              Cancel:
                value:
                  $ref: 'examples\6.0.0\Buyer\XML\MakegoodGuidelinesCancel.xml'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'

  /seller/makegood/offers:
    post:
      tags:
        - Seller
      summary: Receive Makegood Offer
      description: >
        Seller sends to Buyer one or many offer requests to support the following:
        Makegood to resolve unresolved Preemptions
        "ADU" to resolve make-up for audience shortfall
        Supported Transaction Types: New, Change, Cancel, Recall
      operationId: SellerMakegoodOffers
      requestBody:
        description: MakegoodOffers
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SellerMakegoodOffersRequest'
            examples:
              New:
                value:
                  $ref: 'examples\6.0.0\Seller\JSON\MakegoodOffersNew.json'
              Change:
                value:
                  $ref: 'examples\6.0.0\Seller\JSON\MakegoodOffersChange.json'
              Cancel:
                value:
                  $ref: 'examples\6.0.0\Seller\JSON\MakegoodOffersCancel.json'
              Recall:
                value:
                  $ref: 'examples\6.0.0\Seller\JSON\MakegoodOffersRecall.json'
          application/xml:
            schema:
              $ref: '#/components/schemas/SellerMakegoodOffersRequest'
            examples:
              New:
                value:
                  $ref: 'examples\6.0.0\Seller\XML\MakegoodOffersNew.xml'
              Change:
                value:
                  $ref: 'examples\6.0.0\Seller\XML\MakegoodOffersChange.xml'
              Cancel:
                value:
                  $ref: 'examples\6.0.0\Seller\XML\MakegoodOffersCancel.xml'
              Recall:
                value:
                  $ref: 'examples\6.0.0\Seller\XML\MakegoodOffersRecall.xml'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'

  /buyer/makegood/offers:
    post:
      tags:
        - Buyer
      summary: Buyer confirms or rejects Makegood Offers received from the seller
      description: |
        Allows the buyer to respond to an makegood offer(s) with an acceptance confirmation; this will accept all makegood offers in the request.
        Supported Transaction Types: Reject, Confirm
      operationId: BuyerMakegoodOffers
      requestBody:
        description: Makegood offer accept or reject request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuyerMakegoodOffersRequest'
            examples:
              Confirm:
                value:
                  $ref: 'examples\6.0.0\Buyer\JSON\MakegoodOffersConfirm.json'
              Reject:
                value:
                  $ref: 'examples\6.0.0\Buyer\JSON\MakegoodOffersReject.json'
          application/xml:
            schema:
              $ref: '#/components/schemas/BuyerMakegoodOffersRequest'
            examples:
              Confirm:
                value:
                  $ref: 'examples\6.0.0\Buyer\XML\MakegoodOffersConfirm.xml'
              Reject:
                value:
                  $ref: 'examples\6.0.0\Buyer\XML\MakegoodOffersReject.xml'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    BuyerMakegoodGuidelinesRequest:
      oneOf:
        - $ref: './schemas/makegoodsSchemas.yaml#/components/schemas/BuyerMakegoodGuidelines'
        - $ref: './schemas/commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
      xml:
        name: BuyerMakegoodGuidelinesRequest
    SellerMakegoodOffersRequest:
      oneOf:
        - $ref: './schemas/makegoodsSchemas.yaml#/components/schemas/SellerMakegoodOffers'
        - $ref: './schemas/commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
      xml:
        name: SellerMakegoodOffersRequest
    BuyerMakegoodOffersRequest:
      allOf:
        -   $ref:   'schemas/commonSchemas.yaml#/components/schemas/CancelConfirmRecallReject'
      xml:
        name: BuyerMakegoodOffersRequest
