openapi: "3.0.0"
security:
  - bearerAuth: []
info:
  version: 6.1.0
  title: Seller delivers political competitive information to the buyer
  description: >-
    Allows the seller to send to the buyer the political competitive information. No Request from buyer is required.
    Supported Transaction Types: New
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io/v6.0.0
paths:
  /seller/politicalCompetitive:
    post:
      tags:
        - Seller
      summary: Allows the seller to send to the buyer the political competitive information. No Request from buyer is required.
      description: >- 
        Allows the seller to send to the buyer the political competitive information. No Request from buyer is required.
        Supported Transaction Types: New			
      operationId: SellerPoliticalCompetitive
      requestBody:
        description: Top level element for PoliticalCompetitive Seller.
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/politicalCompetitiveness.yaml#/components/schemas/SellerPoliticalCompetitives'
          application/xml:
            schema:
              $ref: './schemas/politicalCompetitiveness.yaml#/components/schemas/SellerPoliticalCompetitives'
      responses:
        '200': #OK
          $ref: 'schemas/commonResponses.yaml#/components/responses/Success'
        '400': #Bad Request
          $ref: 'schemas/commonResponses.yaml#/components/responses/BadRequest'
        '401': #Unauthorized
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unauthorized'
        '403': #Forbidden
          $ref: 'schemas/commonResponses.yaml#/components/responses/Forbidden'
        '404': #Not Found
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotFound'
        '405': #Not Allowed
          $ref: 'schemas/commonResponses.yaml#/components/responses/NotAllowed'
        default: #unexpected
          $ref: 'schemas/commonResponses.yaml#/components/responses/Unexpected'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
